### ISSUE TITLE
Get single process agent working

### ISSUE THREAD

**Issue by cheempz** [appoptics/appoptics-apm-ruby#3]
Asana: https://app.asana.com/0/348434637351502/348739426159148
PR: https://github.com/librato/ruby-tracelytics/pull/1

# Reference
https://github.com/librato/trace/blob/master/docs/

google drive that has most current agent docs: https://drive.google.com/drive/u/0/folders/0Bz1Edylz2u9yNFlOaHZoWWtxdk0
* doc that captures T2 instrumentation questions / decisions: https://docs.google.com/a/librato.com/document/d/1IdSQ_vjIShv_Ck9zvX8JfZ6g461uJEmz6vfCJRADvDs/edit?usp=sharing
* spreadsheet of support matrix we'll aim for in T2: https://docs.google.com/spreadsheets/d/17KXSG274pXIRS8gWHAdd0bnLYV-CzvS-LnE23fLzooQ/edit#gid=73274782

corresponding Python agent PR: https://github.com/librato/python-traceview/pull/8

# Acceptance Criteria
## building
- [x] some way to retrieve the c-lib (liboboe) build artifacts from [S3 rc-files-t2/c-lib bucket](https://console.aws.amazon.com/s3/buckets/rc-files-t2/c-lib/?region=us-east-1&tab=overview) as part of the build process.  Done in https://github.com/librato/ruby-tracelytics/pull/1 -- defines a [rake task](https://github.com/librato/ruby-tracelytics/pull/1/files#diff-52c976fc38ed2b4e3b1192f8a8e24cff) to do this. 

## installing
- [x] single-step install, i.e. just need to `gem install traceview`. Done in https://github.com/librato/ruby-tracelytics/pull/1
- [x] test: multiple installs on the same host, for example under bundler or rbenv environments, expectation is each would use its own bundled c-lib (liboboe). Done in https://github.com/librato/ruby-tracelytics/pull/1

## configuring
- [x] add ability to locally configure `TraceView::Config[:service_key]`
- [x] test: the environment variables `TRACELYTICS_SERVICE_KEY` takes precedence over `TraceView::Config[:service_key]`
- [x] test: getting [diagnostic logging from the c-lib](https://github.com/librato/oboe/wiki/Configure-Diagnostic-Logging#setting-the-detail-level-in-ruby) is important now that it's doing so much, please check that `TRACELYTICS_DEBUG_LEVEL` works.

## startup
- [x] reports [init message](https://github.com/librato/trace/blob/master/docs/specs/init-message.md)

## tracing
- [x] agent should not sample until settings are available.  Our agents used to fall back to some hardcoded defaults, but they should not do that anymore.  Discussion in [the question doc](https://docs.google.com/document/d/1IdSQ_vjIShv_Ck9zvX8JfZ6g461uJEmz6vfCJRADvDs/edit#heading=h.icte6qaeu5i0) -- this probably doesn't require any changes in the Ruby agent as it should rely on `oboe_sample_layer()` to decide whether to trace, which was updated in https://github.com/librato/oboe/commit/99a8c7645f1afc1d81e5e6387d12a77be30e051f#diff-95790fca60c5e490516184761d3be919

- [x] local tracing mode and sample rate should still work -- we don't advertise the `TraceView::Config[:sample_rate]` agent config but it is useful in cases where the collector does not push down the desired setting.  The local sample rate and trace mode settings should take precedence over what is provided by the collector (but only once a setting has been sent down by the collector, i.e. local config are not "default fallback" values used for sampling decision).  Some more on how the c-library currently supports [setting these](https://github.com/librato/oboe/issues/592). 

- [x] remove X-TV-Meta extraction / propagation, similar to librato/joboe#573

- [x] no-op / hide Real User Monitoring (RUM) support, similar to librato/joboe/issues/544
